version: '3'

services:
  main:
    build:
      context: './app'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
      - '8000:8000'
    volumes:
      - './app:/app'
      - './example-volume:/mounted-volume'
    environment:
      - 'NODE_ENV=development'
      - 'UID=1000'
      - 'GID=1000'
